GET http://localhost:3000/shoppingcart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQmVyZGFuIiwiaWF0IjoxNjg3ODQ4OTQ2fQ.IDTR8hFdLwfa3TFeUC-P2NJnouCaOyuRzQtwkiWz2x4
###

DELETE http://localhost:3000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNTY4NzU5OTIyfQ.RT6wszuCeFLwC_6ksmNMIELxiC5s-uRivfRxyZof5ag"
}

###


POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "Berdan",
  "password": "tiki"
}

###

POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "Berdan",
    "password": "tiki"
}

###

GET http://localhost:3000/test
