GET http://localhost:3000/shoppingcart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQmVyZGFuIiwiaWF0IjoxNjg3ODU0MzU3fQ.O7sJkdq2ePEzhGIq1a4e4H04OzhKmJpqBIeloHlBrIw
###

DELETE http://localhost:3000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNTY4NzU5OTIyfQ.RT6wszuCeFLwC_6ksmNMIELxiC5s-uRivfRxyZof5ag"
}

###


POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "Berdan",
  "password": "tiki"
}

###

POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "Berdan",
    "password": "tiki"
}

###

PUT http://localhost:3000/addToShoppingcart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQmVyZGFuIiwiaWF0IjoxNjg3ODU0NjU4fQ.Lbr6oxl_CMYlcRnpG_JDP85m9bgcfXujCP_hPaqRYQw
Content-Type: application/json

{
  "items": ["Fisch", "Granit", "Hund"]
}

