module.exports = {
  1234567: {
    recipeID: "1234567",
    name: "Limestone Dessert",
    stone: "Limestone",
    ingredients: [
      "200g Limestone",
      "100g Sugar",
      "Juice of 2 Lemons",
      "100ml Cream",
      "Mint leaves for decoration",
    ],
    instructions: [
      "Crush the Limestone into small pieces.",
      "In a bowl, mix the crushed Limestone, sugar, and lemon juice.",
      "Whip the cream until stiff peaks form, then gently fold it into the Limestone mixture.",
      "Fill dessert glasses with the mixture and refrigerate for at least 2 hours.",
      "Decorate with mint leaves before serving.",
    ],
    cuisine: "Dessert",
  },
  2345678: {
    recipeID: "2345678",
    name: "Basalt Chocolate Cake",
    stone: "Basalt",
    ingredients: [
      "200g Basalt",
      "200g Dark Chocolate",
      "200g Butter",
      "200g Sugar",
      "4 Eggs",
      "150g Flour",
      "1 tsp Baking Powder",
      "Pinch of Salt",
    ],
    instructions: [
      "Crush the Basalt into fine crumbs.",
      "Melt the dark chocolate and butter in a double boiler.",
      "In a bowl, beat sugar and eggs until creamy.",
      "Add the melted chocolate and mix well.",
      "Sift flour, baking powder, and salt, then stir into the chocolate mixture.",
      "Gently fold in the Basalt crumbs.",
      "Pour the batter into a greased baking pan and bake in a preheated oven at 180°C for about 30-35 minutes.",
      "Allow the cake to cool, then garnish with chocolate glaze or powdered sugar.",
    ],
    cuisine: "Dessert",
  },
  3456789: {
    recipeID: "3456789",
    name: "Slate Cheese Board",
    stone: "Slate",
    ingredients: ["200g Slate", "Assorted Cheese", "Grapes", "Nuts", "Honey"],
    instructions: [
      "Thoroughly clean and dry the Slate.",
      "Arrange the cheeses on the Slate and garnish with grapes and nuts.",
      "Drizzle honey over the cheese, if desired.",
      "Use the Slate as a stylish serving board for the cheese platter.",
    ],
    cuisine: "Appetizer",
  },
  4567890: {
    recipeID: "4567890",
    name: "Marble Pastry",
    stone: "Marble",
    ingredients: [
      "200g Marble",
      "300g Flour",
      "150g Butter",
      "100g Sugar",
      "1 Egg",
      "1 tsp Vanilla Extract",
      "Pinch of Salt",
    ],
    instructions: [
      "Crush the Marble into fine crumbs.",
      "In a bowl, mix flour, butter, sugar, egg, vanilla extract, and salt, and knead into a dough.",
      "Gently fold in the Marble crumbs.",
      "Form the dough into a ball, wrap it in plastic wrap, and let it rest in the refrigerator for at least 30 minutes.",
      "Roll out the dough on a floured surface and cut into desired shapes.",
      "Place the pastry shapes on a baking sheet lined with parchment paper and bake in a preheated oven at 180°C for about 12-15 minutes, or until golden brown.",
      "Allow the Marble Pastries to cool before serving.",
    ],
    cuisine: "Dessert",
  },
  5678901: {
    recipeID: "5678901",
    name: "Granite Soup",
    stone: "Granite",
    ingredients: [
      "200g Granite",
      "1 onion, chopped",
      "2 garlic cloves, chopped",
      "2 carrots, diced",
      "2 celery stalks, diced",
      "1 liter vegetable broth",
      "200ml cream",
      "Salt and pepper to taste",
      "Chopped parsley for garnish",
    ],
    instructions: [
      "Break the Granite into small pieces.",
      "Heat some oil in a large pot and sauté onion, garlic, carrots, and celery in it.",
      "Add the Granite pieces and vegetable broth, and bring it to a boil.",
      "Reduce the heat and let the soup simmer for about 20-25 minutes until the vegetables are soft.",
      "Puree the soup until smooth.",
      "Add the cream and mix well.",
      "Season the soup with salt and pepper.",
      "Fill bowls with the Granite Soup and garnish with chopped parsley.",
    ],
    cuisine: "Soup",
  },
  6789012: {
    recipeID: "6789012",
    name: "Sandstone Salad",
    stone: "Sandstone",
    ingredients: [
      "200g Sandstone",
      "Mixed green salad",
      "Cherry tomatoes",
      "Cucumbers",
      "Olive oil",
      "Lemon juice",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Crumble the Sandstone into small pieces.",
      "Place mixed green salad, cherry tomatoes, and cucumbers in a bowl.",
      "Sprinkle the Sandstone over the salad.",
      "Drizzle olive oil and lemon juice over the salad, and mix well.",
      "Season with salt and pepper.",
      "Serve the Sandstone Salad.",
    ],
    cuisine: "Salad",
  },
  7890123: {
    recipeID: "7890123",
    name: "Quartzite Dessert",
    stone: "Quartzite",
    ingredients: [
      "200g Quartzite",
      "200ml cream",
      "50g sugar",
      "1 tsp vanilla extract",
      "Fruits for decoration",
    ],
    instructions: [
      "Grind the Quartzite into fine powder.",
      "In a bowl, whip the cream, sugar, and vanilla extract until stiff peaks form.",
      "Gently fold the Quartzite powder into the whipped cream.",
      "Fill the mixture into dessert glasses and refrigerate for at least 2 hours.",
      "Decorate with fresh fruits before serving.",
    ],
    cuisine: "Dessert",
  },
  8901234: {
    recipeID: "8901234",
    name: "Quartz Beverage Infusion",
    stone: "Quartz",
    ingredients: [
      "200g Quartz",
      "1 liter water",
      "Fruits or herbs of choice",
    ],
    instructions: [
      "Thoroughly clean the Quartz.",
      "Bring the water to a boil and add the Quartz.",
      "Let the water simmer with the Quartz for about 15 minutes to release the flavors.",
      "Reduce the heat and let the water cool.",
      "Add the desired fruits or herbs and let the water infuse with the Quartz for at least 2 hours.",
      "Remove the Quartz and pour the infused water into glasses.",
      "Serve the Quartz Beverage Infusion chilled.",
    ],
    cuisine: "Beverage",
  },
  1234567: {
    recipeID: "1234567",
    name: "Amethyst Berry Smoothie",
    stone: "Amethyst",
    ingredients: [
      "200g Amethyst stones",
      "1 cup mixed berries",
      "1 banana",
      "1 cup almond milk",
      "1 tablespoon honey",
      "Ice cubes",
    ],
    instructions: [
      "Wash and clean the Amethyst stones thoroughly.",
      "In a blender, combine the Amethyst stones, mixed berries, banana, almond milk, honey, and a handful of ice cubes.",
      "Blend until smooth and creamy.",
      "Pour the Amethyst Berry Smoothie into glasses and serve chilled.",
    ],
    cuisine: "Smoothie",
  },
  2345678: {
    recipeID: "2345678",
    name: "Onyx Caramel Truffles",
    stone: "Onyx",
    ingredients: [
      "200g Onyx stones",
      "1 cup heavy cream",
      "1 cup dark chocolate, chopped",
      "1/2 cup caramel sauce",
      "Cocoa powder for dusting",
    ],
    instructions: [
      "Finely crush the Onyx stones into powder.",
      "In a saucepan, heat the heavy cream until it simmers.",
      "Remove from heat and add the chopped dark chocolate.",
      "Let it sit for a minute, then stir until the chocolate is completely melted and the mixture is smooth.",
      "Add the crushed Onyx powder and caramel sauce to the chocolate mixture. Stir well to combine.",
      "Refrigerate the mixture for about 2 hours until firm.",
      "Scoop small portions of the mixture and roll into truffle balls.",
      "Dust the Onyx Caramel Truffles with cocoa powder.",
      "Store in an airtight container in the refrigerator until ready to serve.",
    ],
    cuisine: "Dessert",
  },
  3456789: {
    recipeID: "3456789",
    name: "Topaz Citrus Salad",
    ingredients: [
      "200g Topaz stones",
      "Mixed salad greens",
      "Oranges, segmented",
      "Grapefruit, segmented",
      "Pomegranate seeds",
      "Honey",
      "Lemon juice",
      "Olive oil",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Thinly slice the Topaz stones.",
      "In a large bowl, combine the mixed salad greens, orange segments, grapefruit segments, and pomegranate seeds.",
      "Arrange the Topaz slices on top of the salad.",
      "In a small bowl, whisk together honey, lemon juice, olive oil, salt, and pepper to make the dressing.",
      "Drizzle the dressing over the Topaz Citrus Salad and toss gently to coat.",
      "Serve chilled.",
    ],
    cuisine: "Salad",
  },
  4567890: {
    recipeID: "4567890",
    name: "Ruby Berry Marinade",
    ingredients: [
      "200g Ruby stones",
      "1/4 cup olive oil",
      "2 tablespoons balsamic vinegar",
      "2 tablespoons honey",
      "1 tablespoon soy sauce",
      "1 teaspoon Dijon mustard",
      "1 cup mixed berries, mashed",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Crush the Ruby stones into small pieces.",
      "In a bowl, whisk together olive oil, balsamic vinegar, honey, soy sauce, Dijon mustard, and mashed mixed berries.",
      "Add the crushed Ruby stones to the marinade and mix well.",
      "Season with salt and pepper to taste.",
      "Marinate your choice of meat (such as chicken or beef) in the Ruby Berry Marinade for at least 30 minutes.",
      "Grill or cook the marinated meat according to your preference.",
      "Serve the cooked meat with additional marinade drizzled on top.",
    ],
    cuisine: "Marinade",
  },
  9012345: {
    recipeID: "9012345",
    name: "Jade Salad",
    stone: "Jade",
    ingredients: [
      "200g Jade stones",
      "Mixed salad greens",
      "Cucumbers",
      "Avocado",
      "Lemon juice",
      "Olive oil",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Slice the Jade stones thinly.",
      "In a large bowl, combine the mixed salad greens, cucumbers, and avocado.",
      "Layer the sliced Jade stones on top of the salad.",
      "Drizzle lemon juice, olive oil, salt, and pepper over the salad, and toss well to combine.",
      "Serve the Jade Salad.",
    ],
    cuisine: "Salad",
  },
  1234560: {
    recipeID: "1234560",
    name: "Obsidian Sushi",
    stone: "Obsidian",
    ingredients: [
      "200g Obsidian stones",
      "Sushi rice",
      "Fresh fish (salmon, tuna, etc.)",
      "Nori seaweed sheets",
      "Soy sauce",
      "Ginger",
      "Wasabi",
    ],
    instructions: [
      "Slice the Obsidian stones into thin pieces.",
      "Cook the sushi rice according to the instructions and let it cool.",
      "Place a sheet of nori seaweed on a sushi mat.",
      "Spread the sushi rice evenly on the nori seaweed.",
      "Place fresh fish and Obsidian slices on top of the rice.",
      "Roll the sushi tightly using the sushi mat.",
      "Cut the roll into small pieces.",
      "Serve with soy sauce, ginger, and wasabi.",
    ],
    cuisine: "Sushi",
  },
  };
  